In [1]:
import numpy as np

In [2]:
numbers  = np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]
150
30.0
50

In [5]:
print(np.shape(numbers))
print(np.ndim(numbers))
print(np.size(numbers))

(5,)

5

In [ ]:
print(np.sum(numbers))
print(np.mean(numbers))
print(np.max(numbers))
print(np.min(numbers))

In [3]:
print(numbers > 25)

[False False  True  True  True]

In [4]:
print(numbers[numbers > 25])

[30 40 50]

In [24]:
print(numbers * 2.5)

[ 25.  50.  75. 100. 125.]

In [26]:
dn = np.array([[100,200,300],[200,400,300]])
print(dn)

[[100 200 300]
 [200 400 300]]

In [27]:
print(np.shape(dn))
print(np.ndim(dn))
print(np.size(dn))

(2, 3)
2
6

In [28]:
print(np.sum(dn, axis=1))

[600 900]

In [6]:
import pandas as pd

In [7]:
sales = pd.Series([1000,1020,1040,1060])
print(sales)

0    1000
1    1020
2    1040
3    1060
dtype: int64

In [8]:
print(sales.sum())

4120

In [9]:
sales_idex = pd.Series([10,20,30,40],index=["A","B","C","D"])
print(sales_idex)

A    10
B    20
C    30
D    40
dtype: int64

In [10]:
data = {
    "product" : ["laptop", "mobile", "keyboard"],
    "price" : [999,888,777],
    "Quantity" : [3,8,5]
}

df = pd.DataFrame(data)
print(df)

    product  price  Quantity
0    laptop    999         3
1    mobile    888         8
2  keyboard    777         5

In [11]:
df["revenue"] = df["price"]*df["Quantity"]
df

    product  price  Quantity  revenue
0    laptop    999         3     2997
1    mobile    888         8     7104
2  keyboard    777         5     3885

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   3 non-null      object
 1   price     3 non-null      int64
 2   Quantity  3 non-null      int64
 3   revenue   3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes

In [13]:
df.shape

(3, 4)

In [14]:
df.columns

Index(['product', 'price', 'Quantity', 'revenue'], dtype='object')

In [15]:
df.describe()

       price  Quantity      revenue
count    3.0  3.000000     3.000000
mean   888.0  5.333333  4662.000000
std    111.0  2.516611  2160.939379
min    777.0  3.000000  2997.000000
25%    832.5  4.000000  3441.000000
50%    888.0  5.000000  3885.000000
75%    943.5  6.500000  5494.500000
max    999.0  8.000000  7104.000000

In [19]:
df.isnull().count()

product     3
price       3
Quantity    3
revenue     3
dtype: int64

In [20]:
df.nunique()

product     3
price       3
Quantity    3
revenue     3
dtype: int64