In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import pandas as pd

file_path = "/content/drive/MyDrive/DTCC/training/data_foundations/data/Pluvial_Flood_Dataset.xlsx"

df = pd.read_excel(file_path)

df.head()

,X,Y,Slope,Curvature,Aspect,TWI,FA,Drainage,Rainfall,SUSCEP
0,3.909444,7.443056,46.686142,-3.888000e+09,45.000000,-3.250368,147.0,228.8528,101.515616,Very_High
1,3.908611,7.442778,52.151768,1.296000e+09,60.945396,-4.313832,61.0,229.6781,80.409863,Very_High
2,3.908889,7.442778,66.484085,0.000000e+00,67.619865,-8.327622,1.0,230.5920,78.986849,Very_High
3,3.909167,7.442778,58.007183,-2.592000e+09,38.659809,-4.707937,51.0,235.4210,81.953151,Very_High
4,3.909444,7.442778,60.503792,-1.296000e+09,351.869904,-5.985817,15.0,234.4346,85.866027,Very_High

In [7]:
df.tail()

,X,Y,Slope,Curvature,Aspect,TWI,FA,Drainage,Rainfall,SUSCEP
144396,3.864167,7.311667,70.837776,1.296000e+09,272.489563,-8.552538,1.0,211.7292,63.087945,Low
144397,3.864444,7.311667,72.578880,1.296000e+09,295.559967,-9.347733,0.0,220.4144,60.489041,Moderate
144398,3.864722,7.311667,70.667946,6.480000e+09,322.125031,-9.236161,0.0,216.3101,62.886849,Low
144399,3.859722,7.311389,61.980232,1.296000e+09,183.814072,-8.819514,0.0,214.3301,66.044932,Low
144400,3.860000,7.311389,68.768135,5.184000e+09,150.945389,-9.134113,0.0,211.5915,101.515616,Low

In [8]:
df.shape

(144401, 10)

In [9]:
df.columns

Index(['X', 'Y', 'Slope', 'Curvature ', 'Aspect', 'TWI', 'FA', 'Drainage',
       'Rainfall', 'SUSCEP'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144401 entries, 0 to 144400
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   X           144401 non-null  float64
 1   Y           144401 non-null  float64
 2   Slope       144119 non-null  float64
 3   Curvature   144401 non-null  float64
 4   Aspect      144401 non-null  float64
 5   TWI         144401 non-null  float64
 6   FA          144401 non-null  float64
 7   Drainage    144401 non-null  float64
 8   Rainfall    144401 non-null  float64
 9   SUSCEP      144401 non-null  object
dtypes: float64(9), object(1)
memory usage: 11.0+ MB

In [11]:
df.describe()

,X,Y,Slope,Curvature,Aspect,TWI,FA,Drainage,Rainfall
count,144401.000000,144401.000000,1.441190e+05,1.444010e+05,1.444010e+05,1.444010e+05,1.444010e+05,144401.000000,144401.000000
mean,3.891534,7.374551,-2.502788e+35,-8.342043e+35,-1.673122e+35,-2.120858e+34,-2.120858e+35,219.714542,74.786932
std,0.027887,0.032459,9.225150e+36,1.682769e+37,7.543591e+36,2.686356e+36,8.492619e+36,7.057921,8.891617
min,3.831111,7.311389,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,203.729300,59.541096
25%,3.868889,7.348333,5.105756e+01,-2.592000e+09,1.013099e+02,-8.654586e+00,0.000000e+00,214.286900,68.140822
50%,3.891667,7.374167,6.198023e+01,0.000000e+00,1.894623e+02,-8.006991e+00,1.000000e+00,220.631300,73.873425
75%,3.913611,7.400278,6.916712e+01,2.592000e+09,2.700000e+02,-6.709276e+00,6.000000e+00,224.191400,81.329315
max,3.954444,7.443056,8.657541e+01,3.888000e+10,3.591449e+02,1.168344e+01,4.579360e+05,235.421000,101.515616

In [12]:
df.describe(include="all")

,X,Y,Slope,Curvature,Aspect,TWI,FA,Drainage,Rainfall,SUSCEP
count,144401.000000,144401.000000,1.441190e+05,1.444010e+05,1.444010e+05,1.444010e+05,1.444010e+05,144401.000000,144401.000000,144401
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38116
mean,3.891534,7.374551,-2.502788e+35,-8.342043e+35,-1.673122e+35,-2.120858e+34,-2.120858e+35,219.714542,74.786932,NaN
std,0.027887,0.032459,9.225150e+36,1.682769e+37,7.543591e+36,2.686356e+36,8.492619e+36,7.057921,8.891617,NaN
min,3.831111,7.311389,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,203.729300,59.541096,NaN
25%,3.868889,7.348333,5.105756e+01,-2.592000e+09,1.013099e+02,-8.654586e+00,0.000000e+00,214.286900,68.140822,NaN
50%,3.891667,7.374167,6.198023e+01,0.000000e+00,1.894623e+02,-8.006991e+00,1.000000e+00,220.631300,73.873425,NaN
75%,3.913611,7.400278,6.916712e+01,2.592000e+09,2.700000e+02,-6.709276e+00,6.000000e+00,224.191400,81.329315,NaN
max,3.954444,7.443056,8.657541e+01,3.888000e+10,3.591449e+02,1.168344e+01,4.579360e+05,235.421000,101.515616,NaN

In [13]:
df.isnull().sum()

X               0
Y               0
Slope         282
Curvature       0
Aspect          0
TWI             0
FA              0
Drainage        0
Rainfall        0
SUSCEP          0
dtype: int64

In [14]:
df.nunique()

X               445
Y               475
Slope           931
Curvature        57
Aspect         2664
TWI           17350
FA             3545
Drainage        197
Rainfall         32
SUSCEP            5
dtype: int64

In [17]:
df[['X','Y']]

               X         Y
0       3.909444  7.443056
1       3.908611  7.442778
2       3.908889  7.442778
3       3.909167  7.442778
4       3.909444  7.442778
...          ...       ...
144396  3.864167  7.311667
144397  3.864444  7.311667
144398  3.864722  7.311667
144399  3.859722  7.311389
144400  3.860000  7.311389

[144401 rows x 2 columns]

In [18]:
df[df['Rainfall']>72]

,X,Y,Slope,Curvature,Aspect,TWI,FA,Drainage,Rainfall,SUSCEP
0,3.909444,7.443056,46.686142,-3.888000e+09,45.000000,-3.250368,147.0,228.8528,101.515616,Very_High
1,3.908611,7.442778,52.151768,1.296000e+09,60.945396,-4.313832,61.0,229.6781,80.409863,Very_High
2,3.908889,7.442778,66.484085,0.000000e+00,67.619865,-8.327622,1.0,230.5920,78.986849,Very_High
3,3.909167,7.442778,58.007183,-2.592000e+09,38.659809,-4.707937,51.0,235.4210,81.953151,Very_High
4,3.909444,7.442778,60.503792,-1.296000e+09,351.869904,-5.985817,15.0,234.4346,85.866027,Very_High
...,...,...,...,...,...,...,...,...,...,...
144383,3.860556,7.311667,52.151768,1.296000e+09,150.945389,-6.649207,5.0,223.4465,72.202740,High
144384,3.860833,7.311667,56.492065,0.000000e+00,114.443954,-7.907903,1.0,216.2673,72.022740,Low
144386,3.861389,7.311667,59.052029,0.000000e+00,102.994614,-8.700139,0.0,213.5930,78.526027,Low
144387,3.861667,7.311667,32.512516,-1.296000e+09,168.690063,-7.738296,0.0,213.1487,73.966027,Low
144400,3.860000,7.311389,68.768135,5.184000e+09,150.945389,-9.134113,0.0,211.5915,101.515616,Low

In [19]:
df[(df['Rainfall']>72) & (df['SUSCEP'] == "Very_High")]

,X,Y,Slope,Curvature,Aspect,TWI,FA,Drainage,Rainfall,SUSCEP
0,3.909444,7.443056,46.686142,-3.888000e+09,45.000000,-3.250368,147.0,228.8528,101.515616,Very_High
1,3.908611,7.442778,52.151768,1.296000e+09,60.945396,-4.313832,61.0,229.6781,80.409863,Very_High
2,3.908889,7.442778,66.484085,0.000000e+00,67.619865,-8.327622,1.0,230.5920,78.986849,Very_High
3,3.909167,7.442778,58.007183,-2.592000e+09,38.659809,-4.707937,51.0,235.4210,81.953151,Very_High
4,3.909444,7.442778,60.503792,-1.296000e+09,351.869904,-5.985817,15.0,234.4346,85.866027,Very_High
...,...,...,...,...,...,...,...,...,...,...
144252,3.880833,7.312500,64.912674,-1.296000e+09,290.556030,-6.175035,15.0,227.2717,83.395342,Very_High
144260,3.883056,7.312500,64.205627,-1.296000e+09,334.983093,-7.817199,2.0,230.0963,83.395342,Very_High
144261,3.883333,7.312500,68.048882,-3.888000e+09,319.085602,-7.998810,2.0,227.4617,75.316164,Very_High
144290,3.891389,7.312500,72.776894,-1.296000e+09,35.537678,-8.666744,1.0,227.0333,85.663014,Very_High
144307,3.862222,7.312222,70.702271,1.296000e+09,23.198591,3.796306,457890.0,227.4831,73.966027,Very_High

In [20]:
df['Rainfall'].mean()

np.float64(74.78693167703749)

In [24]:
df.groupby("SUSCEP")["Rainfall"].mean().sort_values(ascending = False)

SUSCEP
High         74.789881
Moderate     74.787822
Low          74.786956
No_Flood     74.783958
Very_High    74.783165
Name: Rainfall, dtype: float64

In [26]:
features = ['Slope', 'Rainfall', 'FA', 'Drainage']

for col in features:
    min_val = df[col].min()
    max_val = df[col].max()
    df[col + '_norm'] = (
        (df[col] - min_val) / (max_val - min_val)
        if max_val != min_val else 0
    )

In [27]:
df['Risk_Score'] = (
    df['Slope_norm'] * 0.35 +
    df['Rainfall_norm'] * 0.35 +
    df['FA_norm'] * 0.20 +
    (1 - df['Drainage_norm']) * 0.10
) * 100

In [28]:
df

,X,Y,Slope,Curvature,Aspect,TWI,FA,Drainage,Rainfall,SUSCEP,Slope_norm,Rainfall_norm,FA_norm,Drainage_norm,Risk_Score
0,3.909444,7.443056,46.686142,-3.888000e+09,45.000000,-3.250368,147.0,228.8528,101.515616,Very_High,1.0,1.000000,1.0,0.792747,92.072530
1,3.908611,7.442778,52.151768,1.296000e+09,60.945396,-4.313832,61.0,229.6781,80.409863,Very_High,1.0,0.497177,1.0,0.818789,74.213311
2,3.908889,7.442778,66.484085,0.000000e+00,67.619865,-8.327622,1.0,230.5920,78.986849,Very_High,1.0,0.463275,1.0,0.847626,72.738374
3,3.909167,7.442778,58.007183,-2.592000e+09,38.659809,-4.707937,51.0,235.4210,81.953151,Very_High,1.0,0.533944,1.0,1.000000,73.688050
4,3.909444,7.442778,60.503792,-1.296000e+09,351.869904,-5.985817,15.0,234.4346,85.866027,Very_High,1.0,0.627165,1.0,0.968875,77.262008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144396,3.864167,7.311667,70.837776,1.296000e+09,272.489563,-8.552538,1.0,211.7292,63.087945,Low,1.0,0.084500,1.0,0.252429,65.433213
144397,3.864444,7.311667,72.578880,1.296000e+09,295.559967,-9.347733,0.0,220.4144,60.489041,Moderate,1.0,0.022584,1.0,0.526482,60.525617
144398,3.864722,7.311667,70.667946,6.480000e+09,322.125031,-9.236161,0.0,216.3101,62.886849,Low,1.0,0.079709,1.0,0.396975,63.820074
144399,3.859722,7.311389,61.980232,1.296000e+09,183.814072,-8.819514,0.0,214.3301,66.044932,Low,1.0,0.154947,1.0,0.334498,67.078176
144400,3.860000,7.311389,68.768135,5.184000e+09,150.945389,-9.134113,0.0,211.5915,101.515616,Low,1.0,1.000000,1.0,0.248084,97.519161

In [29]:
df['Risk_Level'] = pd.cut(
    df['Risk_Score'],
    bins=[-0.01, 25, 50, 75, 100],
    labels=['Low', 'Moderate', 'High', 'Very_High'],
    include_lowest=True
)

df[['Slope', 'Rainfall', 'Risk_Score', 'Risk_Level']].head()

       Slope    Rainfall  Risk_Score Risk_Level
0  46.686142  101.515616   92.072530  Very_High
1  52.151768   80.409863   74.213311       High
2  66.484085   78.986849   72.738374       High
3  58.007183   81.953151   73.688050       High
4  60.503792   85.866027   77.262008  Very_High

In [30]:
df['Risk_Score'].describe()

count    144119.000000
mean         72.638846
std           7.823868
min           5.138575
25%          67.037541
50%          72.132299
75%          77.736270
max         100.000000
Name: Risk_Score, dtype: float64

In [31]:
df['Risk_Level'].value_counts()

Risk_Level
High         92521
Very_High    51496
Moderate        74
Low             28
Name: count, dtype: int64